name: urmail
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  encrypt: ^5.0.3
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  image: ^4.3.0
  intl: ^0.20.1
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
  assets:
    - assets/profile_pics/default_avatar.png
